= Manual Action Library
_Provengo Core Team_

A library for defining manual actions and validations. Useful for generating https://docs.provengo.tech/ProvengoCli/0.9.5/subcommands/gen-book.html[manual test books], but can also be used as a placeholder actuation layer before a real automation is implemented.

This library supports actions, validations, and notes. There is also support for generating test books steps (for HTML and Excel formats), and common event sets.

TIP: To see an example of this library in action, see the link:wind-bobbin-up[] directory, which contains a Provengo project with manual instructions for https://en.wikipedia.org/wiki/Wind_the_Bobbin_Up[a famous nursery rhyme].

== Installation

To install, place the library's source file, xref:wind-bobbin-up/lib/ManualLib.js[], in the `lib` folder of your project. To download directly from this site, write the following snippet at your project's root directory:

[source, bash]
----
TODO: Correct this
curl https://raw.githubusercontent.com/Provengo/Lib-LuT/main/lib/lut.js > lib/ManualLib.js
----

== Library Reference

CONTPOINT

== Other Places in the Provengoverse

* https://docs.provengo.tech[The Provengo tool Documentation]
* https://www.youtube.com/@provengo[Provengo's YouTube Channel]
* https://provengo.tech[Provengo's Main Site]

---

Enjoy, and we hope you find it useful! Feel free to fork, improve, and share your version of this library!

-- Provengo Engineering